name: Generate Solana Vanity Address

on:
  workflow_dispatch:  # Hanya bisa dijalankan manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check CPU Info
        run: lscpu  # Cek jumlah core CPU yang tersedia

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pynacl base58

      - name: Run Vanity Generator
        run: python solana_vanity.py

      - name: Commit & Push Public Key Only
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add solana_address.txt
          git commit -m "Update Solana Address" || echo "No changes to commit"
          git push

      - name: Save Private Key as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: solana-private-key
          path: solana_private.txt
